### ISSUE TITLE
Windows 64bit Release?

### ISSUE THREAD

**Issue by Wasabi111** [wwu-mmll/deepbet#1]
I got a issue of could not find deepbet when I do pip install deepbet on Windows 11 command line.

**Comment by Wasabi111** [comment]
I wonder if a WIndows 64 bit release version available？Thanks！

**Comment by Wasabi111** [comment]
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting deepbet
  Obtaining dependency information for deepbet from https://files.pythonhosted.org/packages/c5/50/ddb5c44e00157ebbfe5432a6a19e7c5f5c9067b9b974784b687f05e32b9f/deepbet-0.0.1-py3-none-any.whl.metad
ata
  Downloading deepbet-0.0.1-py3-none-any.whl.metadata (3.9 kB)
Collecting connected-components-3d (from deepbet)
  Obtaining dependency information for connected-components-3d from https://files.pythonhosted.org/packages/05/d8/2741b35f24129fc712e505a984fef20ede2e5b58b9a79f4b1560d65486d2/connected_components
_3d-3.12.2-cp38-cp38-win_amd64.whl.metadata
  Downloading connected_components_3d-3.12.2-cp38-cp38-win_amd64.whl.metadata (30 kB)
INFO: pip is looking at multiple versions of deepbet to determine which version is compatible with other requirements. This could take a while.
**ERROR: Could not find a version that satisfies the requirement fill_voids (from deepbet) (from versions: none)
ERROR: No matching distribution found for fill_voids**

**Comment by codingfisch** [comment]
I tried to reproduce the error on a Windows 11 64 bit system but for me "pip install deepbet" worked just fine. 
Are you maybe using Python 2 (Python 3 is needed)?

**Comment by Wasabi111** [comment]
I am using Python 3.8. Maybe I should use a lower version Python?

**Comment by codingfisch** [comment]
Since the issue seems to be that "No matching distribution found for fill_voids" try installing fill_voids with "pip install fill_voids". If that works, run "pip install deepbet" subsequently.

**Comment by Wasabi111** [comment]
It works! Thank you!
