### ISSUE TITLE
zsh: segmentation fault  deepbet-gui

### ISSUE THREAD

**Issue by boddm** [wwu-mmll/deepbet#2]
I installed this package in terminate with the command provided by you. However, when I input the command "deepbet-gui" in terminate, this command "zsh: segmentation fault  deepbet-gui" was outputted. Would you have any approaches to solve it?

**Comment by codingfisch** [comment]
Sorry for the late reply. I am guessing the error is triggered by pyqt. If you haven't already, try to set up a new conda environment and then run 

```bash
pip install deepbet
conda install -c anaconda pyqt=5.15.7
```
If deepbet-gui still results in the error, you still should be able to use deepbet-cli/the python package (see README).

**Comment by codingfisch** [comment]
In the current version (1.0.0), the GUI uses tkinter (python builtin)  to avoid issues around pyqt.
