### ISSUE TITLE
Input Error

### ISSUE THREAD

**Issue by qingfengxulai199** [wwu-mmll/deepbet#3]
![_20240515211746](https://github.com/wwu-mmll/deepbet/assets/148553535/7ac5bdb1-3051-4721-b791-e00519b68785)
NotImplementedError: Input Error: Only 3D, 4D and 5D input Tensors supported (got 5D) for the modes: nearest | linear | bilinear | bicubic | trilinear (got neare
st-exact)

Would you have any approaches to solve it? Your early reply would be highly appreciated.

**Comment by codingfisch** [comment]
The "nearest-exact" interpolation mode requires torch version >= 1.9.0. I will add this dependency requirement in an upcoming release!

**Comment by qingfengxulai199** [comment]
Thank you for your answer, but I still have this problem after upgrading the torch
![Snipaste_2024-05-21_21-24-41](https://github.com/wwu-mmll/deepbet/assets/148553535/7cf24bb4-5c3e-4411-aa0f-c392481ba4f1)

**Comment by codingfisch** [comment]
Sorry, you are right. I have tested it myself and pytorch>=1.11.0 is needed!

**Comment by qingfengxulai199** [comment]
Thank you for your help.
